### ISSUE TITLE
Annotation tool error when annotation smaller than specified size is marked 

### ISSUE THREAD

**Issue by thak123** [Imaginea/vitaFlow#25]
rting xml data to file static/data/annotations/200px-ReceiptSwiss.xml
---------------------------------------------------------------------------------------------------------
127.0.0.1 - - [11/Feb/2019 14:16:23] "POST /inc/validateTagsAndRegions.php HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gaurishk/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gaurishk/Projects/vitaFlow/vitaflow/annotate_server/run.py", line 27, in _rest_validate_tags_and_regions
    return _rest_get_new_image()
  File "/home/gaurishk/Projects/vitaFlow/vitaflow/annotate_server/run.py", line 33, in _rest_get_new_image
    return jsonify(views.GetNewImage.get_new_image())
  File "/home/gaurishk/Projects/vitaFlow/vitaflow/annotate_server/views.py", line 43, in get_new_image
    image_file = [each for each in GetNewImage.ImageFiles.keys() if each.startswith(image_file)][0]
IndexError: list index out of range

**Comment by Mageswaran1989** [comment]
@msampathkumar update plz...

**Comment by msampathkumar** [comment]
Duplicate Ticket

Please refer to https://github.com/Imaginea/vitaFlow/issues/41
